### PR TITLE
benchmark against cpp

### PR DESCRIPTION
**Pull request by Radonirinaunimi**

### CODE REVIEW

**Comment by Radonirinaunimi** [comment]
I think this now could be merged.

**Comment by RoyStegeman** [comment]
I guess so, although it does make the repo a bit of a mess for the time being.

**Comment by Radonirinaunimi** [comment]
> I guess so, although it does make the repo a bit of a mess for the time being.

I can take care of cleaning the repo now, thought this should be merged as it has already achieved its purpose.

**Comment by RoyStegeman** [comment]
Yes you're right, the small-pt problem has been solved. By "mess" I meant that there are some .dat files used by the benchmarking, some notebooks that have been started but probably won't be used anymore and also I think the small-pt fix was only done for the gg channel. Although for now I would just leave these things. Who knows they might be useful in the future, and if not we can remove them once we're really done.

**Comment by Radonirinaunimi** [comment]
> Yes you're right, the small-pt problem has been solved so this PR served it's purpose. By "mess" I meant that there are some .dat files used by the benchmarking, some notebooks that have been started but probably won't be used anymore and also I think the small-pt fix was only done for the gg channel. Although for now I would just leave these things. Who knows they might be useful in the future, and if not we can remove them once we're really done.

Right! By cleaning, I basically meant: (1) going through the notebooks and removing the stuffs that are potentially not correct or not going to be used, (2) add a lynter to the repo such that we have everywhere the same code formatting.

**Pull request merged**
