### PR TITLE
Fix pgg

### PR DESCRIPTION
**Pull request by RoyStegeman**
@Radonirinaunimi can you try this?

### CODE REVIEW

**Comment by Radonirinaunimi** [comment]
I will have a look. For a quick curiosity, does this change the N space results?

**Comment by RoyStegeman** [comment]
Yes this is a bugfix

**Comment by Radonirinaunimi** [comment]
> Yes this is a bugfix

Right, but I was mainly wondering how much does this change the N space results, especially in the large N region (this might improve the agreement between the FO & Threshold expanded). Do you perhaps already have numbers before and after the fixes? I will have a closer look at this as soon as I have time but just curious.

**Comment by Radonirinaunimi** [comment]
I have cross-checked this with the previous results I had and the results are consistent.

**Review by Radonirinaunimi — APPROVED** [review]

**Pull request merged**
