### PR TITLE
add distrcrosspartonic

### PR DESCRIPTION
**Pull request by RoyStegeman**
Good agreement at very small x, as shown by the figure (made using  #8 ). Not so much near N=1, where the disagreement with hpt-n3lo is around a factor 10. 
fig5

### CODE REVIEW

**Comment by RoyStegeman** [comment]
the `tiny` variable has a significant impact at small-N but removing it results in all NaNs. 

At pt=100 and N=1e-3 we find 
for tiny=1e-14: dHdpt = 1.791907e-01
for tiny=1e-15: dHdpt = 2.157278e-01

For the same settings the HE approx in HpT-N3LO gives dHdpt = 1.860239e+01

Also, the pt dependence is not the same for FO and HE (as a result of the `tiny` domain?):
fig6
fig7
Actually, for these plots I removed the - sign of C2 in the HE implementation of n3lo.

**Comment by Radonirinaunimi** [comment]
I will add various plots here that checks all the respective limits in x space first. The reason being that there is still the issue of the position of the poles that do not coincide in the various contributions. From the numbers I've gathered so far, the agreement is not that bad, but will see more in the plots. Concerning the `tiny` restriction, this again might be mainly caused by some numerical errors, but would be good to fully assess its impacts.

**Comment by Radonirinaunimi** [comment]
Below are some plots in x-space of fixed values of `pt`. The two large values of `pt` are the same as in the HE paper while for the small value I just choose `pt=1 GeV`. For some reasons, I couldn't go much below that value as I start to get strange result with hpt-mon. In the plots, there are two different implementations of the HE approximation, one using the same definition of `x` as in the HE paper, and the other one (labelled with `a(xp)`) takes into account the `pt`-dependent term.
nlo_pt1GeV
nlo_pt88GeV
nlo_pt216GeV

For `pt=88, 216 GeV`, the results seem consistent with the ones in the HE paper. Most importantly, the two main issues, namely the difference in signs and magnitudes, now seem to be solved. The results for the modified HE seem to yield too good of an approximation so worth being double-checked. One thing still worries me though. For `pt=1 GeV`, the two results, HE and FO, seem to diverge at small-x. This is very strange as one would expect the HE and the small-pt to coincide for such a value. Since small-pt in `x` space is not implemented yet, it is hard to assess how bad is this result.

**Comment by RoyStegeman** [comment]
Thanks, this seems to confirm what I saw yesterday, except somehow your FO plots appear to be more stable than mine. The divergence for small-pt is a bit curious indeed. What happened to the blue HE line in the first plot?

**Comment by Radonirinaunimi** [comment]
> Thanks, this seems to confirm what I saw yesterday, except somehow your FO plots appear to be more stable than mine. The divergence for small-pt is a bit curious indeed. What happened to the blue HE line in the first plot?

So the first plot confirms the fact that the two definitions of `x` are the same when `pt->0`, thus the curves are lying on top of each other.

**Comment by RoyStegeman** [comment]
Ah right, of course. The lines also seem to suggest that there is one data point at around 1e-4 and then the  next only at 1e-12? Or are the data points in between just perfectly aligned?

**Comment by Radonirinaunimi** [comment]
Here, the `x` bins are divided into log spaced between 1e-12 and 1e-3 and then linearly space from 1e-3 to 9.9e-1. So, yes I'd say that the data points are perfectly aligned between 1e-12 and about 1e-5. The reason is that it is in this region where the log(x) from the HE behavior dominates and then for some reasons there are other terms from the FO that start to kick in from 1e-5 which can be seen in all the plots.

**Pull request closed without merging**
