### PR TITLE
check partonic x-space

### PR DESCRIPTION
**Pull request by Radonirinaunimi**
Benchmark the x-space partonic result with predictions from high-energy resummation.

### CODE REVIEW

**Comment by Radonirinaunimi** [comment]
Bot report from ecf19fe
<details markdown="1">
<summary>Full hadronic</summary>
 
#### LO results (higgspt-hadronic-lo.yaml):
1.000000e+01    1.194234e+00    8.391830e-04
2.000000e+01    4.377814e-01    3.301495e-04
3.000000e+01    2.371806e-01    1.868577e-04
4.000000e+01    1.508852e-01    1.228176e-04
5.000000e+01    1.045529e-01    8.713720e-05
6.000000e+01    7.631876e-02    6.478516e-05
7.000000e+01    5.768089e-02    4.958987e-05
8.000000e+01    4.469820e-02    3.879687e-05
9.000000e+01    3.530277e-02    3.084803e-05
1.000000e+02    2.830855e-02    2.486505e-05
#### NLO results (higgspt-hadronic-nlo.yaml):
1.000000e+01    1.690960e+00    1.149629e-02
2.000000e+01    8.081524e-01    3.505826e-03
3.000000e+01    4.744116e-01    1.683370e-03
4.000000e+01    3.117693e-01    9.748059e-04
5.000000e+01    2.187321e-01    6.256636e-04
6.000000e+01    1.600519e-01    4.280490e-04
7.000000e+01    1.205597e-01    3.059221e-04
8.000000e+01    9.278067e-02    2.258193e-04
9.000000e+01    7.260697e-02    1.709063e-04
1.000000e+02    5.760236e-02    1.319336e-04
</details>
 
<details markdown="1">
<summary>Mellin Partonic</summary>
 
#### LO results (higgspt-partonic-gg-lo.yaml):
1.000000e+01    3.119956e-02    7.025180e-18
2.000000e+01    1.131225e-02    8.409266e-11
3.000000e+01    7.644691e-03    7.025180e-18
4.000000e+01    0.000000e+00    7.025180e-18
5.000000e+01    0.000000e+00    7.025180e-18
6.000000e+01    0.000000e+00    7.025180e-18
7.000000e+01    0.000000e+00    7.025180e-18
8.000000e+01    0.000000e+00    7.025180e-18
9.000000e+01    0.000000e+00    7.025180e-18
1.000000e+02    0.000000e+00    7.025180e-18
#### NLO results (higgspt-partonic-gg-nlo.yaml):
1.000000e+01    0.000000e+00    7.151122e-18
2.000000e+01    0.000000e+00    7.151122e-18
3.000000e+01    0.000000e+00    7.151122e-18
4.000000e+01    0.000000e+00    7.151122e-18
5.000000e+01    0.000000e+00    7.151122e-18
6.000000e+01    0.000000e+00    7.151122e-18
7.000000e+01    0.000000e+00    7.151122e-18
8.000000e+01    0.000000e+00    7.151122e-18
9.000000e+01    0.000000e+00    7.151122e-18
1.000000e+02    0.000000e+00    7.151122e-18
</details>

**Comment by Radonirinaunimi** [comment]
https://github.com/N3PDF/HpT-MON/blob/71b405048fa9945f4113f7e81c2610c213724a91/src/higgsptpartonic.cpp#L911

Why is this term divided by 2? If I remember correctly, in hqt, this is the case because this term appears in two different functions that later on are added up. This is because the `uh` and `th` in this term are not permutted while for the terms above they are. And I think one of the things that we are missing here is exactly the 7th line in eq. (3.17) of G&S.

**Comment by RoyStegeman** [comment]
Indeed the permutation is not implemented but  this is not needed if the rapidity domain is symmetric in y=0.

**Comment by Radonirinaunimi** [comment]
Bot report from 04d8d58
<details markdown="1">
<summary>Full hadronic</summary>
 
#### LO results (higgspt-hadronic-lo.yaml):
1.000000e+01    1.194234e+00    8.391830e-04
2.000000e+01    4.377814e-01    3.301495e-04
3.000000e+01    2.371806e-01    1.868577e-04
4.000000e+01    1.508852e-01    1.228176e-04
5.000000e+01    1.045529e-01    8.713720e-05
6.000000e+01    7.631876e-02    6.478516e-05
7.000000e+01    5.768089e-02    4.958987e-05
8.000000e+01    4.469820e-02    3.879687e-05
9.000000e+01    3.530277e-02    3.084803e-05
1.000000e+02    2.830855e-02    2.486505e-05
#### NLO results (higgspt-hadronic-nlo.yaml):
1.000000e+01    1.690960e+00    1.149629e-02
2.000000e+01    8.081524e-01    3.505826e-03
3.000000e+01    4.744116e-01    1.683370e-03
4.000000e+01    3.117693e-01    9.748059e-04
5.000000e+01    2.187321e-01    6.256636e-04
6.000000e+01    1.600519e-01    4.280490e-04
7.000000e+01    1.205597e-01    3.059221e-04
8.000000e+01    9.278067e-02    2.258193e-04
9.000000e+01    7.260697e-02    1.709063e-04
1.000000e+02    5.760236e-02    1.319336e-04
</details>
 
<details markdown="1">
<summary>Mellin Partonic</summary>
 
#### LO results (higgspt-partonic-gg-lo.yaml):
1.000000e+01    0.000000e+00    7.025180e-18
2.000000e+01    0.000000e+00    7.025180e-18
3.000000e+01    0.000000e+00    7.025180e-18
4.000000e+01    0.000000e+00    7.025180e-18
5.000000e+01    0.000000e+00    7.025180e-18
6.000000e+01    0.000000e+00    7.025180e-18
7.000000e+01    0.000000e+00    7.025180e-18
8.000000e+01    0.000000e+00    7.025180e-18
9.000000e+01    0.000000e+00    7.025180e-18
1.000000e+02    0.000000e+00    7.025180e-18
#### NLO results (higgspt-partonic-gg-nlo.yaml):
1.000000e+01    0.000000e+00    7.151122e-18
2.000000e+01    0.000000e+00    7.151122e-18
3.000000e+01    0.000000e+00    7.151122e-18
4.000000e+01    0.000000e+00    7.151122e-18
5.000000e+01    0.000000e+00    7.151122e-18
6.000000e+01    0.000000e+00    7.151122e-18
7.000000e+01    0.000000e+00    7.151122e-18
8.000000e+01    0.000000e+00    7.151122e-18
9.000000e+01    0.000000e+00    7.151122e-18
1.000000e+02    0.000000e+00    7.151122e-18
</details>

**Pull request merged**
